import type { CardDefinition, CardId } from '../types/card';

export const CARD_DEFINITIONS: Record<CardId, CardDefinition> = {
  scout_left: {
    id: 'scout_left',
    nameCs: 'Průzkum – Levé křídlo',
    category: 'positional',
    section: 'left',
    maxActivations: 1,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: true,
    generalOffensive: false,
    description: 'Aktivuj 1 jednotku na levém křídle. Dobeř 2 karty, zahod 1.',
  },
  scout_center: {
    id: 'scout_center',
    nameCs: 'Průzkum – Střed',
    category: 'positional',
    section: 'center',
    maxActivations: 1,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: true,
    generalOffensive: false,
    description: 'Aktivuj 1 jednotku ve středu. Dobeř 2 karty, zahod 1.',
  },
  scout_right: {
    id: 'scout_right',
    nameCs: 'Průzkum – Pravé křídlo',
    category: 'positional',
    section: 'right',
    maxActivations: 1,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: true,
    generalOffensive: false,
    description: 'Aktivuj 1 jednotku na pravém křídle. Dobeř 2 karty, zahod 1.',
  },
  skirmish_left: {
    id: 'skirmish_left',
    nameCs: 'Šarvátka – Levé křídlo',
    category: 'positional',
    section: 'left',
    maxActivations: 2,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 2 jednotky na levém křídle.',
  },
  skirmish_center: {
    id: 'skirmish_center',
    nameCs: 'Šarvátka – Střed',
    category: 'positional',
    section: 'center',
    maxActivations: 2,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 2 jednotky ve středu.',
  },
  skirmish_right: {
    id: 'skirmish_right',
    nameCs: 'Šarvátka – Pravé křídlo',
    category: 'positional',
    section: 'right',
    maxActivations: 2,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 2 jednotky na pravém křídle.',
  },
  attack_left: {
    id: 'attack_left',
    nameCs: 'Útok – Levé křídlo',
    category: 'positional',
    section: 'left',
    maxActivations: 3,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 3 jednotky na levém křídle.',
  },
  attack_center: {
    id: 'attack_center',
    nameCs: 'Útok – Střed',
    category: 'positional',
    section: 'center',
    maxActivations: 3,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 3 jednotky ve středu.',
  },
  attack_right: {
    id: 'attack_right',
    nameCs: 'Útok – Pravé křídlo',
    category: 'positional',
    section: 'right',
    maxActivations: 3,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 3 jednotky na pravém křídle.',
  },
  coordinated_advance: {
    id: 'coordinated_advance',
    nameCs: 'Koordinovaný postup',
    category: 'positional',
    section: 'any',
    maxActivations: 3,
    unitTypeFilter: 'one_per_section',
    sectionRestricted: false,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj 1 jednotku v každé sekci (levé, středu, pravém).',
  },
  cavalry_charge: {
    id: 'cavalry_charge',
    nameCs: 'Jízdní zteč',
    category: 'tactical',
    section: 'any',
    maxActivations: 3,
    unitTypeFilter: 'cavalry',
    sectionRestricted: false,
    moveBonus: 1,
    attackBonus: 1,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 3 jízdní jednotky kdekoliv. Pohyb +1, Útok +1.',
  },
  direct_fire: {
    id: 'direct_fire',
    nameCs: 'Přímá palba',
    category: 'tactical',
    section: 'any',
    maxActivations: 3,
    unitTypeFilter: 'ranged',
    sectionRestricted: false,
    moveBonus: 0,
    attackBonus: 1,
    noMoveAllowed: true,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj až 3 střelce nebo jízdní lučištníky. Nemohou se pohybovat. Útok +1.',
  },
  inspiring_commander: {
    id: 'inspiring_commander',
    nameCs: 'Inspirativní velitel',
    category: 'tactical',
    section: 'any',
    maxActivations: 2,
    unitTypeFilter: 'any',
    sectionRestricted: false,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: false,
    description: 'Aktivuj libovolné 2 jednotky kdekoliv.',
  },
  general_offensive: {
    id: 'general_offensive',
    nameCs: 'Generální ofenzíva',
    category: 'tactical',
    section: 'any',
    maxActivations: 99,
    unitTypeFilter: 'any',
    sectionRestricted: true,
    moveBonus: 0,
    attackBonus: 0,
    noMoveAllowed: false,
    scoutDraw: false,
    generalOffensive: true,
    description: 'Vyber 1 sekci. Všechny tvé jednotky v ní se mohou pohnout o 1 a zaútočit.',
  },
  // ── Campaign event cards ────────────────────────────────────────────────
  theodora_event: {
    id: 'theodora_event',
    nameCs: 'Theodora: „Purpur je nejlepší rubáš"',
    category: 'tactical',
    section: 'any',
    maxActivations: 1,
    unitTypeFilter: 'any',
    sectionRestricted: false,
    moveBonus: 0,
    attackBonus: 2,        // +2 kostky pro 1 aktivovanou jednotku
    noMoveAllowed: false,
    scoutDraw: true,       // „+1 karta" — využijeme existující scout mechaniku (draw 2, discard 1 → net +1)
    generalOffensive: false,
    description: 'Theodořina inspirace: aktivuj 1 jednotku s +2 kostkami útoku a dobeř si další kartu.',
  },
};

// How many copies of each card in the shared deck (total 14 cards)
export const DECK_COMPOSITION: Partial<Record<CardId, number>> = {
  scout_left: 1, scout_center: 1, scout_right: 1,
  skirmish_left: 1, skirmish_center: 1, skirmish_right: 1,
  attack_left: 1, attack_center: 1, attack_right: 1,
  coordinated_advance: 1,
  cavalry_charge: 1,
  direct_fire: 1,
  inspiring_commander: 1,
  general_offensive: 1,
};
