import type { UnitDefinition, UnitType } from '../types/unit';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  light_infantry: {
    type: 'light_infantry',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    hitAndRun: false,
    breakthrough: false,
    parthianShot: false,
    reducedMeleeDefense: false,
    movedAttackPenalty: false,
    meleeAttackPenalty: false,
    nameCs: 'Lehká pěchota',
    abbrevCs: 'LP',
  },
  heavy_infantry: {
    type: 'heavy_infantry',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 3,
    hitAndRun: false,
    breakthrough: false,
    parthianShot: false,
    reducedMeleeDefense: false,
    movedAttackPenalty: false,
    meleeAttackPenalty: false,
    nameCs: 'Těžká pěchota',
    abbrevCs: 'TP',
  },
  archers: {
    type: 'archers',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,   // can attack adjacent, but with -1 die (meleeAttackPenalty)
    rangeMax: 3,
    attack: 2,
    maxHp: 3,
    hitAndRun: false,
    breakthrough: false,
    parthianShot: false,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,  // -1 die when attacking at dist=1
    nameCs: 'Střelci',
    abbrevCs: 'ST',
  },
  light_cavalry: {
    type: 'light_cavalry',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    breakthrough: false,
    parthianShot: false,
    reducedMeleeDefense: false,
    movedAttackPenalty: false,
    meleeAttackPenalty: false,
    nameCs: 'Lehká jízda',
    abbrevCs: 'LJ',
  },
  heavy_cavalry: {
    type: 'heavy_cavalry',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    hitAndRun: false,
    breakthrough: true,
    parthianShot: false,
    reducedMeleeDefense: false,
    movedAttackPenalty: false,
    meleeAttackPenalty: false,
    nameCs: 'Těžká jízda',
    abbrevCs: 'TJ',
  },
  horse_archers: {
    type: 'horse_archers',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,   // can attack adjacent with -1 die
    rangeMax: 2,
    attack: 2,
    maxHp: 3,
    hitAndRun: false,
    breakthrough: false,
    parthianShot: true,
    reducedMeleeDefense: true,
    movedAttackPenalty: false,
    meleeAttackPenalty: true,  // -1 die when attacking at dist=1
    nameCs: 'Jízdní lučištníci',
    abbrevCs: 'JL',
  },
};
