import type { UnitDefinition, UnitType } from '../types/unit';

/** Defaults for all optional-behaving flags; lets each def override only what it needs. */
const DEFAULTS = {
  hitAndRun: false,
  breakthrough: false,
  parthianShot: false,
  reducedMeleeDefense: false,
  movedAttackPenalty: false,
  meleeAttackPenalty: false,
  ignoresTerrainStop: false,
  siegeBonus: false,
  panicRetreat: false,
  chargeRequires3Hex: false,
  volleyFireBonus: false,
  pikeWall: false,
  setupRequired: false,
  antiHeavyCavalry: false,
  gunpowderWeapon: false,
  namedHero: false,
  destroysWalls: false,
  hiddenInForest: false,
} as const;

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  // ─── Original units ─────────────────────────────────────────────────────────
  light_infantry: {
    ...DEFAULTS,
    type: 'light_infantry',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    nameCs: 'Lehká pěchota',
    abbrevCs: 'LP',
  },
  heavy_infantry: {
    ...DEFAULTS,
    type: 'heavy_infantry',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 3,
    nameCs: 'Těžká pěchota',
    abbrevCs: 'TP',
  },
  archers: {
    ...DEFAULTS,
    type: 'archers',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 3,
    attack: 2,
    maxHp: 3,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    nameCs: 'Střelci',
    abbrevCs: 'ST',
  },
  light_cavalry: {
    ...DEFAULTS,
    type: 'light_cavalry',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    nameCs: 'Lehká jízda',
    abbrevCs: 'LJ',
  },
  heavy_cavalry: {
    ...DEFAULTS,
    type: 'heavy_cavalry',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    breakthrough: true,
    nameCs: 'Těžká jízda',
    abbrevCs: 'TJ',
  },
  horse_archers: {
    ...DEFAULTS,
    type: 'horse_archers',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 2,
    attack: 2,
    maxHp: 3,
    parthianShot: true,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    nameCs: 'Jízdní lučištníci',
    abbrevCs: 'JL',
  },
  scout: {
    ...DEFAULTS,
    type: 'scout',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 1,
    maxHp: 3,
    hitAndRun: true,
    reducedMeleeDefense: true,
    ignoresTerrainStop: true,
    nameCs: 'Zvěd',
    abbrevCs: 'ZV',
  },
  siege_machine: {
    ...DEFAULTS,
    type: 'siege_machine',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 2,
    attack: 3,
    maxHp: 3,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    siegeBonus: true,
    destroysWalls: true,
    nameCs: 'Obléhací stroj',
    abbrevCs: 'OS',
  },
  elite_guard: {
    ...DEFAULTS,
    type: 'elite_guard',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 5,
    maxHp: 3,
    nameCs: 'Elitní garda',
    abbrevCs: 'EG',
  },
  militia: {
    ...DEFAULTS,
    type: 'militia',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 1,
    maxHp: 2,
    panicRetreat: true,
    nameCs: 'Milice',
    abbrevCs: 'ML',
  },

  // ─── Ancient Rome era ───────────────────────────────────────────────────────

  // Legionář — disciplinovaná římská těžká pěchota s oštěpem (pilum).
  legionary: {
    ...DEFAULTS,
    type: 'legionary',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    activatedAbility: 'pilum',
    nameCs: 'Legionář',
    abbrevCs: 'LG',
  },
  // Auxilia — lehká pěchota, ignoruje "stop" v lese (místní zvědové/pomocníci).
  auxilia: {
    ...DEFAULTS,
    type: 'auxilia',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    ignoresTerrainStop: true,
    nameCs: 'Auxilia',
    abbrevCs: 'AX',
  },
  // Equites — římská lehká jízda s hit-and-run.
  equites: {
    ...DEFAULTS,
    type: 'equites',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    nameCs: 'Equites',
    abbrevCs: 'EQ',
  },
  // Sagittarii — syrští lučištníci, range 3, stejné handicapy jako běžní lučištníci.
  sagittarii: {
    ...DEFAULTS,
    type: 'sagittarii',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 3,
    attack: 2,
    maxHp: 3,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    nameCs: 'Sagittarii',
    abbrevCs: 'SG',
  },
  // Scorpio — římská polní balista; range 4, musí stát klidně.
  scorpio: {
    ...DEFAULTS,
    type: 'scorpio',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 2,
    rangeMax: 4,
    attack: 3,
    maxHp: 2,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    setupRequired: true,
    nameCs: 'Scorpio',
    abbrevCs: 'SC',
  },
  // Praetorian — elitní osobní stráž, velmi silná, pomalá.
  praetorian: {
    ...DEFAULTS,
    type: 'praetorian',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 5,
    maxHp: 3,
    nameCs: 'Praetorián',
    abbrevCs: 'PR',
  },
  // Germánský válečník — lehká pěchota s jednorázovým "válečným řevem".
  germanic_warrior: {
    ...DEFAULTS,
    type: 'germanic_warrior',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    activatedAbility: 'warcry',
    hiddenInForest: true,
    nameCs: 'Germán',
    abbrevCs: 'GR',
  },
  // Framea — germánský oštěpník, range 1–2, slabý.
  framea_thrower: {
    ...DEFAULTS,
    type: 'framea_thrower',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 2,
    attack: 2,
    maxHp: 2,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    hiddenInForest: true,
    nameCs: 'Oštěpník',
    abbrevCs: 'OŠ',
  },
  // Germánský náčelník — silná pěchota, inspirátor.
  germanic_chieftain: {
    ...DEFAULTS,
    type: 'germanic_chieftain',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 3,
    hiddenInForest: true,
    nameCs: 'Náčelník',
    abbrevCs: 'NČ',
  },
  // Arminius — named hero, 1×/hru "signál přepadu".
  arminius: {
    ...DEFAULTS,
    type: 'arminius',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    activatedAbility: 'ambush_signal',
    namedHero: true,
    hiddenInForest: true,
    nameCs: 'Arminius',
    abbrevCs: 'AR',
  },

  // ─── Renaissance / Borgia era ───────────────────────────────────────────────

  // Arkebuzír — range 1–3, způsobuje gunpowder panic, koordinovaná volejová salva.
  arquebusier: {
    ...DEFAULTS,
    type: 'arquebusier',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 3,
    attack: 2,
    maxHp: 2,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    volleyFireBonus: true,
    gunpowderWeapon: true,
    nameCs: 'Arkebuzír',
    abbrevCs: 'AK',
  },
  // Pikenýr — velmi pomalý, "pike wall" proti jízdě.
  pikeman: {
    ...DEFAULTS,
    type: 'pikeman',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    pikeWall: true,
    nameCs: 'Pikenýr',
    abbrevCs: 'PK',
  },
  // Gendarm — francouzská těžká jízda; lance charge (+2 kostky po 3+ hex linii).
  gendarme: {
    ...DEFAULTS,
    type: 'gendarme',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    breakthrough: true,
    chargeRequires3Hex: true,
    nameCs: 'Gendarm',
    abbrevCs: 'GD',
  },
  // Stradiot — lehká jízda s džeridem (range 1–2), ignoruje terrain stop.
  stradiot: {
    ...DEFAULTS,
    type: 'stradiot',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 2,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    ignoresTerrainStop: true,
    nameCs: 'Stradiot',
    abbrevCs: 'SD',
  },
  // Rodelero — meč a štít, +1 kostka proti těžké jízdě.
  rodelero: {
    ...DEFAULTS,
    type: 'rodelero',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 3,
    antiHeavyCavalry: true,
    nameCs: 'Rodelero',
    abbrevCs: 'RD',
  },
  // Kušiník — range 3, −1 útok proti těžké zbroji (handled in combat).
  crossbowman: {
    ...DEFAULTS,
    type: 'crossbowman',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 3,
    attack: 3,
    maxHp: 3,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    nameCs: 'Kušiník',
    abbrevCs: 'KU',
  },
  // Kulverina — polní dělo; ničí hradby, range 1–5, setup required.
  culverin: {
    ...DEFAULTS,
    type: 'culverin',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 2,
    rangeMax: 5,
    attack: 4,
    maxHp: 2,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    siegeBonus: true,
    destroysWalls: true,
    setupRequired: true,
    gunpowderWeapon: true,
    nameCs: 'Kulverina',
    abbrevCs: 'KV',
  },
  // Kondotiér — těžká jízda, mercenary loyalty check at start of each turn (in reducer).
  condottiero: {
    ...DEFAULTS,
    type: 'condottiero',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 3,
    breakthrough: true,
    nameCs: 'Kondotiér',
    abbrevCs: 'KD',
  },
  // Caterina Sforza — named defender, inspirační aura, high HP.
  caterina_sforza: {
    ...DEFAULTS,
    type: 'caterina_sforza',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 5,
    namedHero: true,
    // Inspirational aura — adjacent Cilicia defenders ignore one retreat result
    auraEffect: {
      descriptionCs: 'Inspirace Cateriny: sousední obránci ignorují ústup',
      radius: 1,
      targetFilter: {
        faction: 'cilicia',
        excludeSourceUnit: true,
      },
      effect: {
        ignoresRetreat: true,
      },
    },
    nameCs: 'Caterina Sforza',
    abbrevCs: 'CS',
  },
  // Cesare Borgia — named attacker, 1×/hru "zrada".
  cesare_borgia: {
    ...DEFAULTS,
    type: 'cesare_borgia',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 5,
    activatedAbility: 'betrayal',
    namedHero: true,
    nameCs: 'Cesare Borgia',
    abbrevCs: 'CB',
  },

  // ─── Kampaň: Belisariova éra (VI. století) ────────────────────────────────

  // Belisarius — hlavní hráčská hrdina, named hero + commander
  belisarius: {
    ...DEFAULTS,
    type: 'belisarius',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 5,
    namedHero: true,
    isCommander: true,
    nameCs: 'Belisarius',
    abbrevCs: 'BE',
  },

  // Bukelárii — perzistentní elitní jízda s XP (bonusy se aplikují za běhu)
  bucelarii: {
    ...DEFAULTS,
    type: 'bucelarii',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    namedHero: false,
    nameCs: 'Bukelárii',
    abbrevCs: 'BK',
  },

  // Katafrakti — těžká obrněná jízda, odemykatelné přes Favor/Rada
  cataphract: {
    ...DEFAULTS,
    type: 'cataphract',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    breakthrough: true,
    nameCs: 'Katafrakti',
    abbrevCs: 'KA',
  },

  // Isaurijská horská pěchota — +1 v kopcích (aplikuje se přes aura-self)
  isaurian_infantry: {
    ...DEFAULTS,
    type: 'isaurian_infantry',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    nameCs: 'Isaurijci',
    abbrevCs: 'IS',
  },

  // Herulové — berserkeři, +1 útok stabilně, −1 obrana (v counter-attacku)
  heruli: {
    ...DEFAULTS,
    type: 'heruli',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 3,
    reducedMeleeDefense: true,  // −1 obrana vyjádřena přes existující flag
    nameCs: 'Herulové',
    abbrevCs: 'HE',
  },

  // Maurijští oštěpníci — skirmisher, hit-and-run, range 1–2
  mauri_spearmen: {
    ...DEFAULTS,
    type: 'mauri_spearmen',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 2,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    nameCs: 'Mauri',
    abbrevCs: 'MA',
  },

  // ─── Peršané ──────────────────────────────────────────────────────────────

  persian_immortal: {
    ...DEFAULTS,
    type: 'persian_immortal',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    nameCs: 'Nesmrtelní',
    abbrevCs: 'NS',
  },

  persian_cavalry: {
    ...DEFAULTS,
    type: 'persian_cavalry',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    nameCs: 'Perská jízda',
    abbrevCs: 'PJ',
  },

  // Slon — pomalý, silný; panic při 2+ zásazích (handled in combat via flag)
  elephant: {
    ...DEFAULTS,
    type: 'elephant',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    nameCs: 'Slon',
    abbrevCs: 'SL',
  },

  // Firouz — perský velitel (persian_cavalry + isCommander)
  firouz: {
    ...DEFAULTS,
    type: 'firouz',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Firouze: všechny perské jednotky mají −1 kostku útoku',
      effect: { attackDice: -1 },
      durationTurns: 1,
      affectUnitTypes: ['persian_immortal', 'persian_cavalry', 'elephant', 'archers', 'sagittarii'],
    },
    nameCs: 'Firouz',
    abbrevCs: 'FR',
  },

  // ─── Nika povstalci ───────────────────────────────────────────────────────

  civilian_mob: {
    ...DEFAULTS,
    type: 'civilian_mob',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 1,
    maxHp: 5,
    panicRetreat: true,
    nameCs: 'Dav',
    abbrevCs: 'DV',
  },

  stone_throwing_mob: {
    ...DEFAULTS,
    type: 'stone_throwing_mob',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 2,
    attack: 1,
    maxHp: 5,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    panicRetreat: true,
    nameCs: 'Dav s kameny',
    abbrevCs: 'DK',
  },

  // Hypatius — vůdce povstání (named + commander)
  hypatius: {
    ...DEFAULTS,
    type: 'hypatius',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 5,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Hypatia: demoralizace povstalců (−1 útok)',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['civilian_mob', 'stone_throwing_mob', 'pompeius'],
    },
    nameCs: 'Hypatius',
    abbrevCs: 'HY',
  },

  pompeius: {
    ...DEFAULTS,
    type: 'pompeius',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 5,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Pompeia: demoralizace povstalců (−1 útok)',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['civilian_mob', 'stone_throwing_mob', 'hypatius'],
    },
    nameCs: 'Pompeius',
    abbrevCs: 'PM',
  },

  // ─── Vandalové (Ad Decimum / Tricamarum) ──────────────────────────────────

  vandal_cavalry: {
    ...DEFAULTS,
    type: 'vandal_cavalry',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    nameCs: 'Vandalská jízda',
    abbrevCs: 'VJ',
  },

  vandal_infantry: {
    ...DEFAULTS,
    type: 'vandal_infantry',
    unitClass: 'light',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 4,
    nameCs: 'Vandalská pěchota',
    abbrevCs: 'VP',
  },

  // Ammatas — vandalský velitel
  ammatas: {
    ...DEFAULTS,
    type: 'ammatas',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Ammatase: Vandali −1 kostka útoku',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['vandal_cavalry', 'vandal_infantry', 'gelimer', 'tzazon'],
    },
    nameCs: 'Ammatas',
    abbrevCs: 'AM',
  },

  gelimer: {
    ...DEFAULTS,
    type: 'gelimer',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    isCommander: true,
    nameCs: 'Gelimer',
    abbrevCs: 'GE',
  },

  tzazon: {
    ...DEFAULTS,
    type: 'tzazon',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    breakthrough: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Tzazona: Gelimer v panice 1 kolo',
      effect: { cannotMove: true },
      durationTurns: 1,
      affectUnitTypes: ['gelimer'],
    },
    nameCs: 'Tzazon',
    abbrevCs: 'TZ',
  },

  // ─── Campaign Fáze 2 — Tricamarum & Neapol ────────────────────────────────

  // Jan Arménský — byzantský commander, charge +1 po pohybu 2+ hexů
  jan_armenian: {
    ...DEFAULTS,
    type: 'jan_armenian',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    breakthrough: true,
    chargeRequires3Hex: true,  // +2 kostky po 3+ hex v linii (reused flag)
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Jana Arménského: byzantská jízda −1 kostka útoku (2 kola)',
      affectFaction: 'cilicia',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['heavy_cavalry', 'horse_archers', 'light_cavalry', 'bucelarii', 'cataphract', 'mauri_spearmen'],
    },
    nameCs: 'Jan Arménský',
    abbrevCs: 'JA',
  },

  // Obléhací věž — pomalá struktura, pohyb 1, žádný útok; při dosažení hradby
  // umožní průchod pěchoty sousedícím hexem po 2 kola.
  siege_tower: {
    ...DEFAULTS,
    type: 'siege_tower',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 0,
    rangeMax: 0,
    attack: 0,
    maxHp: 3,
    reducedMeleeDefense: true,
    nameCs: 'Obléhací věž',
    abbrevCs: 'OV',
  },

  // Obléhací beran — destroysWalls flag; malé HP; specializovaný na brány
  siege_ram: {
    ...DEFAULTS,
    type: 'siege_ram',
    unitClass: 'heavy',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 2,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    destroysWalls: true,  // může mlátit do gate/wall hexů
    nameCs: 'Beran',
    abbrevCs: 'BR',
  },

  // Gotická pěchota — solidní heavy infantry
  gothic_infantry: {
    ...DEFAULTS,
    type: 'gothic_infantry',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    nameCs: 'Gotická pěchota',
    abbrevCs: 'GP',
  },

  // Gotický rytíř — těžká jízda s chargeBonus (reusing chargeRequires3Hex)
  gothic_knight: {
    ...DEFAULTS,
    type: 'gothic_knight',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    breakthrough: true,
    chargeRequires3Hex: true,
    nameCs: 'Gotický rytíř',
    abbrevCs: 'GR',
  },

  // Gotická milice — vysoká HP, slabý útok; +1 obrana ve městě (implementováno
  // přes panicRetreat flag = retreat ignoruje při obrane; simplifikace).
  gothic_militia: {
    ...DEFAULTS,
    type: 'gothic_militia',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 1,
    attack: 2,
    maxHp: 5,
    nameCs: 'Gotická milice',
    abbrevCs: 'GM',
  },

  // Gotičtí lučištníci — na hradbách (+1 dostřel handle via elevation)
  gothic_archers: {
    ...DEFAULTS,
    type: 'gothic_archers',
    unitClass: 'light',
    move: 1,
    rangeMin: 1,
    rangeMax: 3,
    attack: 2,
    maxHp: 3,
    reducedMeleeDefense: true,
    movedAttackPenalty: true,
    meleeAttackPenalty: true,
    nameCs: 'Gotičtí lučištníci',
    abbrevCs: 'GL',
  },

  // ─── Campaign Fáze 3 — Obrana Říma & Epilog ───────────────────────────────

  // Witiges — gótský král, obléhatel Říma; namedHero + commander
  witiges: {
    ...DEFAULTS,
    type: 'witiges',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    breakthrough: true,
    chargeRequires3Hex: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Witigese: gotičtí útočníci −1 kostka útoku (2 kola)',
      affectFaction: 'tamerlane',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['gothic_infantry', 'gothic_knight', 'gothic_militia', 'gothic_archers'],
    },
    nameCs: 'Witiges',
    abbrevCs: 'WI',
  },

  // Hunnic horde — rychlá lehká jízda ze stepí (Epilog A)
  hunnic_horde: {
    ...DEFAULTS,
    type: 'hunnic_horde',
    unitClass: 'light',
    move: 3,
    rangeMin: 1,
    rangeMax: 2,
    attack: 2,
    maxHp: 3,
    hitAndRun: true,
    parthianShot: true,
    reducedMeleeDefense: true,
    meleeAttackPenalty: true,
    nameCs: 'Hunská horda',
    abbrevCs: 'HH',
  },

  // Zabergan — hunský chán (Epilog A Konstantinopol); commander + aura
  zabergan: {
    ...DEFAULTS,
    type: 'zabergan',
    unitClass: 'heavy',
    move: 3,
    rangeMin: 1,
    rangeMax: 1,
    attack: 3,
    maxHp: 4,
    hitAndRun: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Zabergana: Hunové −1 kostka útoku (2 kola)',
      affectFaction: 'tamerlane',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['hunnic_horde', 'horse_archers'],
    },
    nameCs: 'Zabergan',
    abbrevCs: 'ZA',
  },

  // Totila — aura +1 útok všem Gótům ve 3 hexech; commander
  totila: {
    ...DEFAULTS,
    type: 'totila',
    unitClass: 'heavy',
    move: 2,
    rangeMin: 1,
    rangeMax: 1,
    attack: 4,
    maxHp: 4,
    breakthrough: true,
    chargeRequires3Hex: true,
    isCommander: true,
    commanderDeathEffect: {
      descriptionCs: 'Pád Totily: gotické jednotky −1 kostka útoku (2 kola)',
      affectFaction: 'tamerlane',
      effect: { attackDice: -1 },
      durationTurns: 2,
      affectUnitTypes: ['gothic_infantry', 'gothic_knight', 'gothic_militia', 'gothic_archers'],
    },
    auraEffect: {
      descriptionCs: 'Totilova inspirace: gotické jednotky ve 3 hexech +1 útok',
      radius: 3,
      targetFilter: {
        faction: 'tamerlane',
        unitTypes: ['gothic_infantry', 'gothic_knight', 'gothic_militia', 'gothic_archers'],
        excludeSourceUnit: true,
      },
      effect: { attackDice: 1 },
    },
    nameCs: 'Totila',
    abbrevCs: 'TO',
  },
};
